<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action is incorrect' => 'Неправильное действие',
    'Action not defined' => 'Не указано действие',
    'File not found' => 'Файл не найден',
    'Incorrect request' => 'Не верный запрос',
    'Missing meta data for file' => 'Не найдены данные файла',
    'Wrong generated link' => 'Не правильно сгенерирована ссылка',
    'Wrong module name! You need call this method with right fileProcessor module name.' => 'Не правильное имя модуля! Вы дожны вызывать этот метод используя правильное имя модуля fileProcessor',
];
